### ISSUE TITLE
CNPHI Export Header Issues - sequencing centre, primary specimen id, #version

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#111]
Issues with DataHarmonizer -> CNPHI Export Headers:
- Does _not include_ "**Sequencing Centre**" field which is mandatory for CNPHI upload.
- CNPHI will _not accept_ the field name "**primary specimen identification number**", it is expecting "**primary specimen id**".
- CNPHI will _not accept_ uploads that have the **DataHarmonizer version information**, e.g. "#validated using data harmonizer version 0.13.1". At least, not on the header row.

**Comment by cmrn-rhi** [comment]
Can put a hold on this until we meet with CNPHI on Friday 2020-Oct-16.
Will update then.

**Comment by cmrn-rhi** [comment]
**Updates** - we need to implement to following changes:

1. Include a "**Sequencing Centre**" field.
2. Change "**Primary Specimen Identification Number**" to "**Primary Specimen ID**".
3. Remove the "**#validated using data harmonizer version 0.13.1**" etc. output from the header row. Lev is going to send me a field name that they use for additional comments that we can output that information into for each observation.

**Comment by cmrn-rhi** [comment]
1. @cmrn-rhi will add a "Sequencing Centre" picklist to the "DataHarmonizer Templates" document that will be used to populate the new field.

**Comment by ddooley** [comment]
I did that already!
And will make change to code to handle the "#validated using ... " message better. We need a way to control, for each template or export format, whether it is added, and under what column label.

**Comment by ddooley** [comment]
Ah, though I see you mention "picklist" so setting up some values for the field.  Its a select field then.

**Comment by cmrn-rhi** [comment]
Yes! I just made it a select field and added the list from the CNPHI template to the DataHarmonizer templates.

**Comment by ddooley** [comment]
At moment test data doesn't validate on the new Sequencing Centre selections. But I have all the field changes working except waiting for new comments field for version.

**Comment by ddooley** [comment]
I've set it up so that on any template, we can specify a field of datatype = provenance which at moment then receives a "DataHarmonizer vX.Y.Z" value in first row of that column's data - but only if you press "Validate".  So we can talk about what kind of functionality tweaks we should have for this, i.e. do we
- want dataharmonizer version to be included anytime someone saves the file, or just updated when someone presses Validate?
- want the version info to be written to every row of output data?
One can actually put other content in the provenance field.  Version will always be inserted before that content.
The specification is shown in the CanCoGen Covid19 tab, on line 120.
This is demonstrated on the multi-template DataHarmonizer website.

**Comment by ddooley** [comment]
Resolved that version info is written to each row of output data.

**Comment by cmrn-rhi** [comment]
Having an issue with `primary specimen id` now as there appear to be some leading characters that make it unrecognizable to CNPHI. I can see these chars when view with UTF-7 encoding.

![image](https://user-images.githubusercontent.com/48695054/98069128-e975fb00-1e12-11eb-81ef-d44f41abd038.png)

**Comment by cmrn-rhi** [comment]
leading characters = `ï»¿`

**Comment by ddooley** [comment]
Can you send me the test file containing this?  Is it in header row?  Not seeing it in some saved Laser dataset.

**Comment by cmrn-rhi** [comment]
Sent via SLACK.

I'm also seeing those leading chars in files I saved from DataHarmonizer yesterday. Looking at some previous DH1 testing I did (October 6th, 2020) and neither the saved files nor CNPHI export had these leading characters in them.

**Comment by ddooley** [comment]
Ok, so in the current javascript generated export file, there is a BOM header that is often included with UTF-8 to indicate that the file is encoded in UTF-8.  Unpleasant that CNPHI objects to the presence of this on import because these same characters enable Excel to recognize a comma delimited file as such. I'm just checking that out and determining whether those characters can be safely dropped or if we have to tailor something just for the CNPHI export.

**Comment by ddooley** [comment]
Technical note: I’m thinking of switching file export output for ".csv" and ".txt" files to UTF-16 with no BOM.  Looks like the easiest way to do that is have “txt” as the booktype rather than “csv” (while keeping the delimiters appropriate for csv and tsv).

**Comment by ddooley** [comment]
Solution was to create a special .csv output format encoded as UTF-8 but without the BOM.  Awaiting test on whether that works with character sets going into CNPHI. Alternately we force output format to ASCII.

**Comment by cmrn-rhi** [comment]
CNPHI now accepts the import; however, they don't appear to accept symbols in UTF-8 (at least not _greater than or equa_l to, and _degree_)

**CNPHI Upload Error:**
![image](https://user-images.githubusercontent.com/48695054/98301312-64ecbf00-1f6f-11eb-81d8-9f0c92c8eaba.png)

Have emailed NML/CNPHI liaison outlining these issues and asked:

1. Does CNPHI require ASCII text?
2. Are there other acceptable characters for mathematical logic?
3. Would it be possible for CNPHI to accept the BOM?

**Comment by ddooley** [comment]
This might be fixed now with a .csv (ASCII) format save. Awaiting testing.

**Comment by cmrn-rhi** [comment]
.csv (ASCII) format has been tested and there have been no further issues.
