### ISSUE TITLE
Paste a value to an entire column

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#164]
Often data entry requires pasting the same value to an entire column, for every sample e.g. lab name or collection date precision value.

Keyboard shortcuts don't work in the DH so a user has to highlight all the rows before pasting which is very laborious and time consuming when working with thousands of rows. 

Can we have a feature that enables copy-pasting to an entire column (where cells correspond to samples)?

**Comment by cmrn-rhi** [comment]
#### DH v 13.19 - Windows 10.0.18363 OS 
Interesting, I find I am able to _copy-paste_ entire columns after selecting the column header and using keyboard macros on Windows without problem... at least _within_ the DataHarmonizer. I am also able to do it from other spreadsheets, however, instead of just _pasting_ as normal the column ends up **replicating** what is being _pasted_ in subsequent rows.

Example (Copy-Paste Originating Spreadsheet):
```
row   1   abc
row   2   xyz
row   3   123
row   4   000
```
Example (Copy-Paste into DataHarmonizer `specimen collector sample ID`):
```
row   1   abc
row   2   xyz
row   3   123
row   4   000
row   5   abc
row   6   xyz
row   7   123
row   8   000
row   9   abc
row  10   xyz
```
I tried doing this a few times in `specimen collector sample ID` and the same degree of repetition occurred.
I also tried copy-pasting into `bioproject accession` and the contents were were repeated even more.

**Comment by cmrn-rhi** [comment]
Just to clarify, are these the kind of behaviours you're talking about?

> Keyboard shortcuts don't work in the DH so a user has to highlight all the rows before pasting which is very laborious and time consuming when working with thousands of rows.

Example - Copy-Paste Rows (Current):

![DH13 19-20210413_CanCoGen-copy-paste-row-selection](https://user-images.githubusercontent.com/48695054/114598735-15f63480-9c47-11eb-9e27-05dadd1e2e02.gif)

> Can we have a feature that enables copy-pasting to an entire column (where cells correspond to samples)?

Example - Copy-Paste Column (Desired): 

![DH13 19-20210413_CanCoGen-copy-paste-col-selection](https://user-images.githubusercontent.com/48695054/114599024-6a99af80-9c47-11eb-96ba-6cf5bd1cae17.gif)

(after pasting it jumps the view to the end of the spreadsheet)

**Comment by ddooley** [comment]
So Emma is the workaround that you were after: Copy the value (id) into cut and paste buffer.  Select column header and  press paste, and get entire column filled with given id?

**Comment by griffie** [comment]
Yeah! Copy value, select column header and press paste and all the cells associated with samples get filled with that value.

If there are only 5 samples, only 5 rows in the column should get that value, not all 500 cells or whatever the DH goes up to.

**Comment by ddooley** [comment]
I see, so that remains a problem that would require a custom solution for.

**Comment by ddooley** [comment]
This functionality is now running in test branch. Empty rows will not have column cells updated.
